version: '3'

services:
  node:
    build: ./containers/node
    volumes:
      - ./mnt/node:/mnt
      - node_node_modules:/mnt/my-app/node_modules # for svelte
      - firebase_functions_node_modules:/mnt/my-app/functions/node_modules # for firebase
    tty: true
    ports:
      - '5173:5173'
      - '4173:4173'
      - '6006:6006'
      - '4000:4000' # firebase emu gui
      - '4500:4500' # firebase emu logging
      - '5001:5001' # firebase emu func
      - '8080:8080' # firebase emu firestore
      - '8085:8085' # firebase emu pubsub
      - '9099:9099' # firebase emu auth
      - '9150:9150' # firebase emu firestore:websocket
      - '9199:9199' # firebase emu storage
      - '9299:9299' # firebase emu eventarc
    working_dir: /mnt

  gcloud:
    build: ./containers/gcloud
    volumes:
      - ./mnt:/mnt
    tty: true
    working_dir: /mnt

volumes:
  node_node_modules:
  firebase_functions_node_modules:
